# 容器 配置
server:
  port:
  ssl:
    key-store: classpath:musclegeeker.jks
    key-password: 214234332560773
  undertow:
    worker-threads: 20
    buffer-size: 512
    io-threads: 2
# 数据库 及 Redis 配置
spring:
  redis:
    host: r-2zecdd4a71259204.redis.rds.aliyuncs.com
    password: Passw0rd
    port: 6379
#  使用 MySQL 不用做任何修改
  datasource:
    url: jdbc:mysql://rm-uf6h84vo5p70438s5o.mysql.rds.aliyuncs.com:3306/appdb?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: P@ssw0rd
    sql-script-encoding: utf-8
    hikari:
      max-lifetime: 1765000
      maximum-pool-size: 10
# Mybatis 配置
mybatis:
  configuration:
    map-underscore-to-camel-case: true    # 驼峰命名转换
